SELECT N,
CASE 
    WHEN NOT EXISTS(SELECT B.P FROM BST AS B WHERE B.P = BST.N) THEN 'Leaf'
    WHEN EXISTS(SELECT B.P FROM BST AS B WHERE B.P = BST.N) THEN
        CASE 
            WHEN EXISTS(SELECT B.P FROM BST AS B WHERE B.N = BST.N AND B.P IS NOT Null) THEN 'Inner'
            ELSE 'Root'
        END
END as q
FROM BST
ORDER BY N
